### ISSUE TITLE
Default master item selection

### ISSUE THREAD

**Issue by eggzotic** [2-5-perceivers/flutter-master-detail-flow#1]
Add arg to constructor MasterDetailFlow.fromItems to specify which item is initially selected and thus which details item is displayed by default. Currently, none of the master items are initially selected. Really enjoying using the Widget - thanks for the great work!

**Comment by raresvanca** [comment]
Hi @eggzotic today I released version 2.0, rebuilt from the ground up. I also added an initialPage parameter as per your request.

https://pub.dev/documentation/master_detail_flow/latest/master_detail_flow/MasterDetailsFlow/initialPage.html
