### ISSUE TITLE
Customization

### ISSUE THREAD

**Issue by maziac** [2-5-perceivers/flutter-master-detail-flow#10]
Hi,
many thanks for that great package.

I'm struggling a little bit with customization, hopefully you can help:
1. I would like to color the MasterItems but haven't found a way to do that. In the end I would like to do some zebra-coloring. I.e. alternate colors for alternating rows.
2. Is there a way to hide the title of the MasterDetailsFlow. Even if title is null it still display a top row.

**Comment by raresvanca** [comment]
Fixed in version 3.0.0
