### ISSUE TITLE
sub navigation

### ISSUE THREAD

**Issue by Aruljebaraj** [2-5-perceivers/flutter-master-detail-flow#11]
assume if the we have a button on the detail part and on press detail part need to be changed exactly same how it works in pad setting page any idea how to implement those?

**Comment by raresvanca** [comment]
You can get the MDController from the context, even in a details page, and use its `selectPage` method

**Comment by raresvanca** [comment]
Here is an example:

```dart
MDController.of(context, listen: false)
            .selectPage('pageID', builder: (_) => Placeholder());
```
